feat: add create branch page
students-4-students/prog pull request #9
Opened 2021-09-06 11:24 UTC by BoyeGuillaume

# Features :
 * add the create-branch page
 * add the `.error` class for an error note
 * add a new example in the *branches.md* file

# Authors
> authors : [ @BoyeGuillaume ]

2021-09-07 13:05 UTC, Nicolapps requested changes
Merci pour ta PR ! Je n’ai pas encore relu la formulation, mais j’ai ajouté quelques commentaires sur le contenu en général.

2021-09-07 13:05 UTC, Nicolapps commented on .gitignore
> +
Pourquoi est-ce que tu veux ignorer le `Gemfile.lock` ? Ce fichier est censé être commit ([source](https://thelazylog.com/you-should-always-commit-gemfile-lock-and-schema-rb/)).

2021-09-07 13:05 UTC, Nicolapps commented on _sass/custom/custom.scss
> +
Merci pour cet ajout ! Par contre, je ne vois pas où tu l’as utilisé dans ta PR, est-ce que c’est normal ?

2021-09-07 13:05 UTC, Nicolapps commented on branches/branches.md
> +</div>
J’ai l’impression que cet exemple n’est pas très clair (les noms très abstraits des branches y joue un rôle). De plus, c’est la même situation que celle présentée sur le schéma de l’exemple précédent. Je pense que ça pourrait être une bonne idée de retirer cette partie, et d’expliquer dans l’exemple précédent que l’on peut changer la branche active à tout moment.

2021-09-07 13:05 UTC, Nicolapps commented on branches/checkout.md
> +# Changer de branche sur le Terminal
Je ne pense pas que ce soit une bonne idée d'inclure des instructions pour le terminal dans ce document. On en avait discuté avec d'autres membres de l'équipe auparavant, et le but est de passer entièrement par l'interface graphique dans le cadre de S4S. C’est important vu la forte différence de niveau entre les différentes personnes que l’on s’attend à avoir.

2021-09-07 13:05 UTC, Nicolapps commented on branches/create.md
> +</div>
Est-ce que tu aurais un exemple dans lequel c’est utile de créer la branche depuis GitHub ? Je ne pense pas que ce soit souvent utilisé, donc j'aurais plutôt tendance à ne pas en parler ici.

2021-09-07 13:05 UTC, Nicolapps commented on branches/checkout.md
> +* [Depuis le Terminal](#changer-de-branche-sur-le-terminal)
Pour cette partie, il vaut mieux utiliser la table de matières générée par Jekyll, tu peux retrouver dans les autres pages le code à utiliser.

2021-09-07 13:05 UTC, Nicolapps commented on branches/create.md
> +
(Même remarque concernant l’utilisation du terminal)

2021-09-07 13:05 UTC, Nicolapps commented on branches/create.md
>  # Créer une nouvelle branche
Vu les commentaires plus bas, j’ai l’impression que ça pourrait valoir la peine de fusionner cette page dans la page indiquant comment changer de branche, pour n’en faire qu’une qui parle des deux. Je peux m’en charger. Qu’en penses-tu ?

2021-09-07 13:49 UTC, BoyeGuillaume commented on .gitignore
> +
Sry, j'ai pas regardé le contenu du fichier. J'ai vue que c'était un .lock et je me suis dit que c'était un fichier pour éviter plusieurs instances d'un même programme de se lancer

2021-09-07 14:19 UTC, BoyeGuillaume commented on branches/create.md
>  # Créer une nouvelle branche
Je pense que c'est une bonne idée. Dans la nouvelle version j'ai merge créer/changer de branche dans une seule page gérer ses branches.

2021-09-10 16:06 UTC, Nicolapps approved these changes
J’ai effectué quelques changements, pour moi c’est prêt à être merge. Est-ce que tout est bon pour toi ?

2021-09-10 16:06 UTC, Nicolapps commented on branches/manage.md
> +Pour pallier a ce problème vous pouvez donc simplement cliquez sur le bouton `Publiez branche` et celle si sera automatiquement mise en ligne.
La partie sur les branches locales/distantes ne me semble pas être utile à ce point car cette page se situe avant la partie *Collaborer*. J’ai déplacé les informations utiles dans cette partie.

2021-09-10 16:06 UTC, Nicolapps commented on _sass/custom/custom.scss
> +
J’ai fix l’espacement des images. Il y avait un souci parce que tes images étaient à l’intérieur du `<p>` au lieu d’être à l’extérieur. Du coup, ce code n’est plus nécessaire.

2021-09-11 13:06 UTC, merged